# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('visibility', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ressource_visibility_pts', models.IntegerField(default=100)),
                ('value_visibility_pts', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='choicapp.Item')),
                ('type_of_vote', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('choicapp.item',),
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='choicapp.Item')),
                ('link', models.URLField(blank=True, null=True)),
            ],
            bases=('choicapp.item',),
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='choicapp.Item')),
                ('definition', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            bases=('choicapp.item',),
        ),
    ]
