# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='voters',
            field=models.ManyToManyField(blank=True, to='choicapp.Voter'),
        ),
    ]
