# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0002_item_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='voters',
        ),
    ]
