# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0003_remove_item_voters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Voted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choicapp.Item')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choicapp.Voter')),
            ],
        ),
    ]
