# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0004_item_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='item_ptr',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='item_ptr',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='value_visibility_pts',
            new_name='value_pts',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='ressource_visibility_pts',
        ),
        migrations.DeleteModel(
            name='Proposition',
        ),
        migrations.DeleteModel(
            name='Ressource',
        ),
    ]
