# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0005_auto_20160410_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='visibility',
            new_name='points',
        ),
    ]
