# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0007_auto_20160410_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBookPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
    ]
