# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0008_logbookpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary_Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
