# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0009_glossary_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='choicapp.Item')),
                ('descriptions', models.TextField()),
                ('deadline', models.DateTimeField()),
            ],
            bases=('choicapp.item',),
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='title',
        ),
    ]
