# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0010_auto_20160501_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='descriptions',
            new_name='description',
        ),
    ]
