# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0011_auto_20160501_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='deadline',
            field=models.DateField(),
        ),
    ]
