# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0012_auto_20160501_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_voted',
            name='vote_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='deadline',
            field=models.DateField(help_text='DD/MM/YYYY'),
        ),
    ]
