# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0013_auto_20160506_1224'),
        ('choicapp', '0013_auto_20160506_1618'),
    ]

    operations = [
    ]
