# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0014_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='value_pts',
            new_name='dokv',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='value',
            name='definition',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voter',
            name='dokp',
            field=models.IntegerField(default=0),
        ),
    ]
