# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0015_auto_20160508_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='status',
            field=models.CharField(choices=[('pending', 'En cours'), ('voted', 'Voté'), ('rejected', 'Rejeté/Expiré')], default='pending', max_length=30),
        ),
    ]
