# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choicapp', '0016_proposition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='status',
            field=models.CharField(choices=[('pending', 'En cours'), ('voted', 'Vote'), ('rejected', 'Rejete/Expire')], default='pending', max_length=30),
        ),
    ]
